name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
      - "infra/docker/backend.Dockerfile"
      - "infra/ci-cd/github-actions/backend-ci.yaml"
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # =====================================================
  # 1. Lint + Test + Validate
  # =====================================================
  build-test:
    name: Lint & Test Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: t79_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (cached)
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Tests
        run: |
          pytest backend/tests --disable-warnings --maxfail=1

      - name: Run FastAPI type checks
        run: |
          echo "Skipping full mypy for now (optional)"

  # =====================================================
  # 2. Docker Image Build & Push
  # =====================================================
  docker-build:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to GHCR (or Docker Hub – optional alternative below)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -- If using Docker Hub instead, uncomment below and remove GHCR login --
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f infra/docker/backend.Dockerfile \
            -t ghcr.io/${{ github.repository }}/t79-backend:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/t79-backend:latest

  # =====================================================
  # 3. Deploy to Kubernetes (Optional)
  # =====================================================
  deploy:
    name: Deploy Backend to Kubernetes
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Kubernetes credentials (store in GitHub Secrets)
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Update image in backend deployment
        run: |
          kubectl set image deployment/t79-backend \
          t79-backend=ghcr.io/${{ github.repository }}/t79-backend:latest \
          -n t79

      - name: Restart rollout
        run: |
          kubectl rollout restart deployment t79-backend -n t79

      - name: Verify deployment status
        run: |
          kubectl rollout status deployment/t79-backend -n t79
