# tools/ice-age/local_trainer.py
import os
import subprocess

def trigger_local_training():
    """
    Launches a local Unsloth session to fine-tune Llama 3.3
    using the IT-data generated by DeepSeek-V3.
    """
    print("❄️ [ICE-AGE] Starting Sovereign Training...")

    # 1. Activate your local environment (Conda/Venv)
    # 2. Run the fine-tuning script in the background
    cmd = "python3 core/training/kaggle_scripts/train_script.py"

    process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    return process.pid

# Link this to your Admin UI button 'START TRAINING'
